#!/usr/bin/perl
$pat=shift || '.*';
print "\$pat=$pat\n";
$pat=qr/$pat/;
open my $jps_out,"jps |" or die "$!";
while(<$jps_out>){
	($pid,$p)=split /\s+/;
	print "$p\n";
	if ($p =~ $pat){
		print "shudown $p(pid=$pid)\n";
		`kill -9 $pid`;
	}
}

