#!/usr/bin/env bash
file=$1;shift
if [ -z $file ];then
	echo "Error: Empty file name!"
	exit 0
elif [ -d $file ];then
	rflag="-r"
elif [ -f $file ];then
	rflag=""
else
	echo "Error: File $file not exists or is not an file/dir name"
	exit 1
fi



function abspath(){
	pushd $1 >/dev/null 2>&1
	pwd
	popd $1 >/dev/null 2>&1
}

dir=`dirname $file`
file=${file##$dir/}
dir=`abspath $dir`
#base=${file%%.*}
#ext=${file##*.}
user=`whoami`
for host in $*;do
	echo ==== scp $rflag $dir/$file $user@$host:$dir/ ====
	scp $rflag $dir/$file $user@$host:$dir/
	echo ====
done
